### ISSUE TITLE
[BUG] Issue with "msaaStaging" in BlueFramework

### ISSUE THREAD

**Issue by pjanck** [tumcms/Open-Infra-Platform#214] opened 2020-08-10 19:45 UTC
**Describe the bug**
After the BlueFramework was recently updated, an error occurs when starting the application:
![grafik](https://user-images.githubusercontent.com/59165496/89823887-83027900-db52-11ea-8453-b6ab67c47af0.png)

**To Reproduce**
1. Build OpenInfraPlatform.UI anew.
2. Start the debugger.

**Expected behavior**
Well, the app does not crash.

**Screenshots**
See above for error message & call stack. Auto variables (it apperas that `msaaStaging` is NULL):
![grafik](https://user-images.githubusercontent.com/59165496/89824263-20f64380-db53-11ea-8a69-61596b1a61cd.png)

**CMake configuration**
 If applicable, list any special configurations you have made in CMake.
- EARLYBINDING_WITH_IFC4x1: selected (reported by @pjanck )
- EARLYBINDING_WITH_IFC4x3_RC1: selected (reported by @SamuilsRulovs and @mauplatteau )

**Additional context**
This happens on the commit 9dac1d0476d35fd1230773928356959eb6073dc8 .

**Comment by Vertexwahn** [comment] 2020-08-11 19:10
The problem is not a missing `KernelBase.dll`.Check the return code of the `copySubresourceRegion`. Please check always all return codes! Before fixing the bug try to come up with a Test the reproduces this error to make sure that does not happen again.

**Comment by pjanck** [comment] 2020-08-13 11:13
The problem is that `msaaStaging=null`. The `msaaStaging.Get()` fails and thus the code itself. I am not aware of how to set the variable to a valid value.

**Comment by pjanck** [comment] 2020-08-13 11:31
Current workaround (as long as the issue is not resolved in BlueFramework):

Within the solution, navigate to the file `D3D11RenderSystem.cpp` under 
> BlueFramework->BlueFramework.D3D11RenderSystem->BlueFramework->D3D11RenderSystem->D3D11RenderSystem.cpp

Comment out lines 280 and 282-287. Build BlueFramework.D3D11RenderSystem anew.

**Comment by pjanck** [comment] 2020-08-13 15:06
Better workaround (like this the Unit tests work as well):

Same file, line 280 should read (add the OR expression):
> if (!getMSAAEnabled() || texture->getMSAAStagingTexture() == nullptr) {

**Comment by hechth** [comment] 2020-08-18 10:28
Fixed in BF 0.0.9

**Closed as completed by hechth** 2020-08-18 10:28 UTC
Labels: bug, help wanted

**Comment by hechth** [comment] 2020-08-18 10:29
> The problem is not a missing `KernelBase.dll`.Check the return code of the `copySubresourceRegion`. Please check always all return codes! Before fixing the bug try to come up with a Test the reproduces this error to make sure that does not happen again.

Doesn't return an error code btw.
